temporary:
   cronExpression: 0 30 20 * * *
   storageDuration: 2

server:
    port: 8604
    error.whitelabel.enabled: false
 
logging:
   file: ../logs/opse-prod.log
   

mail:
    hostname: localhost
    subjectPrefix: '[OPSE]'
    from: northstar@sedoo.fr
 
spring:
    application.name: MTropics
#    boot:
#       admin:
#           client:
#               url: http://127.0.0.1:9999 
#
#endpoints:
#    enabled: true
#    health:
#        enabled: true
#management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#    endpoint:
#        health:
#            show-details: "ALWAYS"
#            northstar:
#                cacheup: 240
#                cachedown: 120




---
spring.profiles: dev

---
spring.profiles: fa

mail.msecContactEmail: noone@gmail.com
mail.sedooContactEmail: noone@gmail.com

dataPolicy: /home/amiere/data1/mtropics/data-policy/*.pdf




---
spring.profiles: am


dataPolicy: /home/openopse/Documents/GitHub/data1/mtropics/data-policy/*.pdf

mail:
    hostname: localhost
    subjectPrefix: '[OPSE]'
    from: arnaud.miere@gmail.com
    

sso:
    login: arnaud.miere@obs-mip.fr
    password: Miere22@r

spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: openopse
      username: openopse
   #   password: ope001
   
openOpse:
    data: /home/amiere/Documents/data/
    depot: /home/amiere/Documents/depot/
local:
    baseFolder: /home/amiere/Documents/tmp/
    
etc.python:
    venvdir: /home/amiere/Documents/python/venv
    scriptdir: /home/amiere/Documents/python/scripts/
    convertMneToPngLauncherScript: convertMneToPng.sh
    spipEtcLauncherScript: SpipLauncher.sh
    etcInstallScript: install.sh


---
spring.profiles: prod

local:
    baseFolder: /data2/opse-prod/tmp

openOpse:
    data: /data/baobab/openopse/openOpse/data
    depot: /data/baobab/openopse/openOpse/depot


etc.python:
    scriptdir: /data2/opse-prod/python/scripts/
    

sso:
    login: arnaud.miere@obs-mip.fr
    password: Miere22@r    
    

spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: openopse
      username: openopse
      password: ope001
